version: '3.8'

services:
  calorie-bot:
    build: .
    container_name: calorie-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db-data: